version: "3.7"

services:
  database:
    image: postgres
    container_name: postgres_databases
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: products_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/products_api
    links:volumes:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
